In [3]:
#隨機取數

import numpy as np

#nump.random.randn():隨機建立資料
for i in range(10):
    a = np.random.randn()
    print(a,end=" ")
    
#np.random.randn(row,col):
a = np.random.randn(2,4)+9. #每一個陣列中的元素雖機產生後會加上9.99
print(a)

-1.00752965981524 0.1617223401818132 0.8858975045741182 0.9168955036812856 0.17729856138300057 -0.5982697952015227 -1.5281851671686677 1.3968452702607506 -0.052746310097574224 0.07660433852288123 [[ 9.73561964  9.18990407  9.12411867  8.84305963]
 [10.30274616 10.94367804  7.9897449   9.66049164]]


In [7]:
#np.random.randint(Low,hight,size=x) size產出幾個

a = np.random.randint(10,20,size=10)
print(a)

b = np.random.randint(10)
print(b)

a=np.random.randint(19,99,size=36)
b = a.reshape(6,6)
print(b)

[15 15 10 17 11 12 14 14 11 11]
5
[[70 66 96 44 60 58]
 [71 70 95 74 35 58]
 [34 57 32 55 26 90]
 [65 36 65 50 96 45]
 [90 51 46 39 59 23]
 [31 42 43 42 47 56]]


In [16]:
a = np.random.randint(10,30,size=9).reshape(3,3)
print(a)
print()
b = np.random.randint(40,60,size=9).reshape(3,3)
print(b)

#算array總和: 有numpy array 改用np.sum 速度運算非常快
sum_all_a = np.sum(a)
sum_all_b = np.sum(b)
print('Array a 總和：', sum_all_a)
print('Array b 總和：', sum_all_b)

#最大值與最小值
max_array_a = np.max(a)
max_array_b = np.max(b)
print("a最大值：", max_array_a ,a.max())
print("b最大值：", max_array_b ,b.max())

print("a最小值：", np.min(a), a.min())
print("b最小值：", np.min(b), b.min())

[[24 29 11]
 [15 27 19]
 [16 26 27]]

[[51 42 45]
 [57 43 44]
 [40 42 44]]
Array a 總和： 194
Array b 總和： 408
a最大值： 29 29
b最大值： 57 57
a最小值： 11
b最小值： 40


In [25]:
#axis=0: (對於每一個column做運算)
#axis=1: (對於每一個row做運算)

a = np.random.randint(10,99,size=24).reshape(4,6)
print(a)
print("列出每一個col的最大值：", a.max(axis=0))
print("列出每一個row的最大值：", a.max(axis=1))

print("列出每一個col的最小值：", a.min(axis=0))
print("列出每一個row的最小值：", a.min(axis=1))

print("列出每一個col的總和：", a.sum(axis=0))
print("列出每一個row的總和：", a.sum(axis=1))

[[50 21 84 58 86 24]
 [31 90 35 62 10 92]
 [98 85 16 55 25 55]
 [10 61 78 33 43 45]]
列出每一個col的最大值： [98 90 84 62 86 92]
列出每一個row的最大值： [86 92 98 78]
列出每一個col的最小值： [10 21 16 33 10 24]
列出每一個row的最小值： [21 10 16 10]
列出每一個col的總和： [189 257 213 208 164 216]
列出每一個row的總和： [323 320 334 270]


In [36]:
a = np.random.randint(1,5,size=24).reshape(4,6)
print(a)
print()

print("Array a的元素乘機: ",        a.prod())
print("Array a的中位數: ",          a.mean())
print("Array a的標準差: ",          a.std())
print("Array a的方差: ",            a.var())
print("Array a的最大值: ",          a.max())
print("Array a的最小值: ",          a.min())
print("Array a的最大值的索引位置: ",  a.argmax())
print("Array a的最小值的索引位置: ",  a.argmin())

[[3 1 4 3 3 4]
 [3 2 3 1 1 3]
 [4 3 3 2 2 4]
 [2 2 2 1 2 4]]

Array a的元素乘機:  859963392
Array a的中位數:  2.5833333333333335
Array a的標準差:  0.9965217285917832
Array a的方差:  0.9930555555555557
Array a的最大值:  4
Array a的最小值:  1
Array a的最大值的索引位置:  2
Array a的最小值的索引位置:  1



In [75]:
import csv
import numpy as np

filename = "data301_2017年全年毛豬交易行情資料.csv"

with open(filename, 'r', encoding="utf-8") as fp:
    data = csv.reader(fp)
    data = list(data)
    data.pop(0) 
#print(data)

 
npdata = np.array(data)


pig = npdata[:,0]
pig = pig.astype(int)
print("有幾頭豬:",sum(pig))

weight = npdata[:,1]
weight = weight.astype(float)
all_weight=pig*weight
print("平均重量:",sum(all_weight)/sum(pig))

price = npdata[:,2]
price = price.astype(float)
all_price=pig*price
a_p = sum(all_weight)/sum(pig)
print("平均價格:",sum(all_price)/sum(pig))

big_pig = pig.argmax()
print("最多有:",big_pig)
bpw = npdata[big_pig:big_pig+1,1]
bpp = npdata[big_pig:big_pig+1,2]
bpw = bpw.astype(float)
bpp = bpp.astype(float)
print("最多豬的重量:",sum(bpw))
print("最多豬的價錢:",sum(bpp))

print(pig.std())
print(all_weight.std())
print(all_price.std())

有幾頭豬: 3383747
平均重量: 124.15736108521104
平均價格: 76.41706164793037
最多有: 1931
最多豬的重量: 127.53
最多豬的價錢: 76.88
747.5817674325009
94263.43306232456
57313.825174051555


1. 眾數: 一群數據中，出現最多次的數資叫做眾數 [2,2,2,2,2,2,4,5,6,7,4,8] =>2出現最多次，眾數=2
2. 中位數: 將一群數據中從小到大排列，取正中間位置的數 
    (數量是奇數的時，中位數排序在中正中間的數) (數量是偶數時，中位數排序在正中間兩數的平均)
        77, 62, 72, 85, 62, 67, 51, 77
    * step1:  51, 62, 62, 67, 72, 77, 77, 85
    * step2:  int((0+7)/2) = 3 index=3與4的數字來做相加除以2: (67+72)/2 = 69.5
3. 平均數: 把所有數字加總除以個數


4. 區間代表數: 用一個數字來代表數據的集中情形，表示數據分散情形
   * 如果區間代表書小，代表書句比較集中
   * 如果區間代表書大，代表書句比較分散
   
    區間代表數: 標準差
     1. 變異數: 所有離均差平方的算術平均數 
     2. 標準差: 將變異數取平方根
     
    數據: 1 3 7 9 10
    
    (1)算術平均數: (1+3+7+9+10)/5=6
    (2)變異數: ((1-6)^2 + (3-6)^2 + (7-6)^2 + (9-6)^2 + (10-6)^2 )/5 = 12
    (3)標準差: 12平方根 = 3.46
    
    資料分析時會用標準差來檢查資料，如果標準差很大，代表資料有極值，額外處理否則會影響到整個數據
