In [1]:
#建立numpy一維陣列:

import numpy as np

a = np.array([1,2,3,4]) #經由傳送List或是tuple給np.array 可以建立一維陣列
b = np.array((0,0,0,0))

print(a,type(a))
print(b,type(b))

[1 2 3 4] <class 'numpy.ndarray'>
[0 0 0 0] <class 'numpy.ndarray'>


In [2]:
#numpy data type常用的資料類型: booleans(bool),integer(int), unsigned in tegers(uint),float(float),complex

c = np.array([1.34,2.41,-8.76],dtype='int')
print(c)

d = np.array([30,20,10],dtype='float')
print(d)

[ 1  2 -8]
[30. 20. 10.]


In [3]:
#np.arange() 給特定數字的範圍來建立array,來加入python range建立array

a = np.arange(3,30,3)
print(a)

b = np.arange(11,100,11)
print(b)

[ 3  6  9 12 15 18 21 24 27]
[11 22 33 44 55 66 77 88 99]


In [4]:
#np.linspace:建立一個間隔相同的的陣列 (start, end, 產生幾個)
c = np.linspace(0,10,5) #間隔計算: (10-0)/4 = 2.5
print(c)

d = np.linspace(0,18,7)
print(d)

[ 0.   2.5  5.   7.5 10. ]
[ 0.  3.  6.  9. 12. 15. 18.]


In [5]:
# numpy array以索引index以及slicing來去存取元素

myarray =np.arange(3,30,3)
print(myarray)
print(myarray[0]) #取得第一個元素
print(myarray[-1]) #取最後一個元素
print(myarray[2:6]) 
print(myarray[1:-1:2]) # slicing[start,stop but not in incloud,step]走兩步拿一個

[ 3  6  9 12 15 18 21 24 27]
3
27
[ 9 12 15 18]
[ 6 12 18 24]


In [6]:
#np.zero:建立全為0的陣列

myarray = np.zeros(6,dtype='int')
print(myarray)
myarray = np.zeros(6)
print(myarray)

myarray = np.ones(6,dtype='int')
print(myarray)
myarray = np.ones(6)
print(myarray)

[0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1.]


In [7]:
myarray = np.arange(3,30,3)
print(myarray)

print(len(myarray)) #陣列中有幾個元素
print(myarray.size) #陣列中有幾個元素

print(myarray.dtype) #陣列中的資料型態
print(myarray.dtype.name) #陣列中的資料型態
print(myarray.ndim) #陣列維度
print(myarray.shape) #(9,): 一為陣列9個元素

[ 3  6  9 12 15 18 21 24 27]
9
9
int64
int64
1
(9,)
