In [1]:
# 1. 可以透過傳送多維串列(List)給np.array,透過np.shape取得array外型

import numpy as np #載入numpy函式，簡短取名為np

two = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(two)
print(two.shape)
print(two.dtype)
print(two.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
int64
12


In [2]:
#2. 一維陣列，利用numpy.reshape，轉成需要的外型

a = np.arange(1,26)
print(a)
b = a.reshape(5,5)
print(b)

print(b[2][4])
print(b[2,4]) #存取b陣列中第二個row與第四個column
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
15
15
(5, 5)


In [3]:
#建立一個array，3x4array,裡面的直從1-12

a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
# 多維陣列以indexing and slicing 來陣列元素的存取

a = np.arange(1,26).reshape(5,5)
print(a)

b = np.zeros(25).reshape(5,5)
print(b)

print(a[0,1:4]) #取得row 0中，第一個-第三個元素產生的一維子陣列
print(a[1:4,0]) #取得col 0中，第一個-第三個row,產生的一維子陣列
print(a[::2,::2]) #取得一個二維子陣列，(0,2,4列) (0,2,4 column) => (0,0),(0,2)(0,4) (2,0),(2,2).....
print(a[: ,1]) #獲取整個column產生的一維子陣列

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[2 3 4]
[ 6 11 16]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
[ 2  7 12 17 22]


In [5]:
#6x6矩陣，矩陣中的元素從二開始為偶數
#(1) 取得row3的所有三素子陣列
#(2) 取得col4的所有元素子陣列
#(3) 取得左上角的3x3的二維子陣列
#(4) 取得元素>20的元素

a = np.arange(2,73,2).reshape(6,6)
print(a)
print(a[3,:]) 
print(a[: ,4]) 
print(a[:3,:3])
a=a.reshape(1,36)
print(a[0,:10])

[[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]
 [26 28 30 32 34 36]
 [38 40 42 44 46 48]
 [50 52 54 56 58 60]
 [62 64 66 68 70 72]]
[38 40 42 44 46 48]
[10 22 34 46 58 70]
[[ 2  4  6]
 [14 16 18]
 [26 28 30]]
[ 2  4  6  8 10 12 14 16 18 20]
