In [1]:
#np.full((shape), value): 將陣列元素作填充

#建立一個3x3矩陣，裡面數直接為9

import numpy as np
a = np.full((3,3),9)
print(a)

b = np.identity(5) #產生對角線為一，其他元素為0的array
print(b)

[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
arr = np.array([[1,2,3,4], [4,5,6,7], [8,9,10,11]])
c   = np.repeat(arr[0], 3, axis=0)
d   = np.repeat(arr   , 3, axis=0)
print(c)
print(d)

arr2 = arr[1]
e    = np.repeat([arr2], 5, axis=0)
print(e)

[1 1 1 2 2 2 3 3 3 4 4 4]
[[ 1  2  3  4]
 [ 1  2  3  4]
 [ 1  2  3  4]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]
 [ 8  9 10 11]]
[[4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]


In [11]:
#numpy排序

x1 = np.array([2,1,4,6,3,5])
x1.sort() #針對numpy array做排序
print(x1)

[1 2 3 4 5 6]


In [12]:
x2 = np.array([2,1,4,6,3,5])
pos = x2.argsort() #第一個元素要的最小索引值，第二個元素要放的第二個最小元素索引值
print(x2)
print(pos)

[2 1 4 6 3 5]
[1 0 4 2 5 3]


In [18]:
#numpy使用axis參數對多維陣列進行行排序，或是列排序

x = np.random.randint(0,10,(4,6))
print(x)
print()

x.sort(axis=0) #以col做排序
print(x)
print()

x.sort(axis=1) #以row做排序
print(x)

[[8 0 8 5 7 1]
 [2 8 3 9 8 6]
 [7 2 0 9 1 4]
 [7 4 7 7 2 6]]

[[2 0 0 5 1 1]
 [7 2 3 7 2 4]
 [7 4 7 9 7 6]
 [8 8 8 9 8 6]]

[[0 0 1 1 2 5]
 [2 2 3 4 7 7]
 [4 6 7 7 7 9]
 [6 8 8 8 8 9]]


In [19]:
#部分排序: 分區 (希望在陣列中找到最小的k個值)
#np.partition: 給一個陣列跟一個數字

x = np.array([7,2,3,1,6,5,4])
x.partition(4)
print(x)

x.partition(2)
print(x)

[2 1 3 4 5 6 7]
[1 2 3 4 5 6 7]
